name: "SQLx Format Checker"
description: "Check if SQL code in sqlx macros needs formatting using sqruff."

inputs:
  context:
    description: "Directory containing Rust files"
    required: false
    default: "."
  config-file:
    description: "Path to sqruff configuration file (.sqruff)"
    required: false
    default: ".sqruff"
  fail-on-unformatted:
    description: "Whether to fail the action if formatting changes are needed"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Build sqlx-fmt
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        cargo build --release

    - name: Check SQL formatting
      shell: bash
      working-directory: ${{ inputs.context }}
      run: |
        set -e

        SQLX_FMT="${{ github.action_path }}/target/release/sqlx-fmt"
        SQLX_FMT_SQRUFF_CONFIG="${{ inputs.config-file }}"
        SQLX_FMT_FAIL_ON_UNFORMATTED="${{ inputs.fail-on-diff }}"

        $SQLX_FMT check

branding:
  icon: "code"
  color: "blue"
