name: "SQLx Format Checker"
description: "Check if SQL code in sqlx macros needs formatting using sqruff."

inputs:
  context:
    description: "Directory containing Rust files"
    required: false
    default: "."
  config-file:
    description: "Path to sqruff configuration file (.sqruff)"
    required: false
    default: ".sqruff"
  fail-on-unformatted:
    description: "Whether to fail the action if formatting changes are needed"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Build sqlx-fmt
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        cargo build --release
        cargo binstall sqruff

    - name: Check SQL formatting
      shell: bash
      uses: cargo-bins/cargo-binstall@main
      working-directory: ${{ inputs.context }}
      run: |
        set -e

        SQLX_FMT="${{ github.action_path }}/target/release/sqlx-fmt"
        export SQLX_FMT_PATH="."
        export SQLX_FMT_SQRUFF_CONFIG="${{ inputs.config-file }}"
        export SQLX_FMT_FAIL_ON_UNFORMATTED="${{ inputs.fail-on-unformatted }}"

        echo "Binary path: $SQLX_FMT"
        echo "Current directory: $(pwd)"
        echo "Binary exists: $(test -f "$SQLX_FMT" && echo 'yes' || echo 'no')"
        echo "Config file: $SQLX_FMT_SQRUFF_CONFIG"
        echo "Fail on unformatted: $SQLX_FMT_FAIL_ON_UNFORMATTED"

        "$SQLX_FMT" check

branding:
  icon: "code"
  color: "blue"
